services:
  media_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=media_admin
      - POSTGRES_PASSWORD=media_admin
      - POSTGRES_DB=mediadb
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/data/:/var/lib/postgresql/data
  media_redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    ports:
      - "6380:6379"
  media_api:
    image: duoeditor/media
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5002:80"
